### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by Jankylulu** [FrogTheFrog/frl-toggle#1]
Hello :) I am new to all this, and I am trying to run the app but its not running. Appreciate some guidance :)

**Comment by FrogTheFrog** [comment]
Heyo, so you need to open the windows terminal/powershell/cmd in order to keep the output.

Then type in something like `.\frltoggle.exe status` and you should get a valid output or an error.

**Comment by FrogTheFrog** [comment]
Afterwards it depends on where do you plan to use it?

**Comment by Jankylulu** [comment]
Thanks! 
So I plan to use this on sunshine. 
What do I need to do if I want to have the FPS set to 90 once sunshine starts, and back to normal when sunshine stops. Sorry if my question is very silly but I'm a noob to all this. Thanks for taking the time to reply 😄

**Comment by FrogTheFrog** [comment]
Ok, so make sure to modify the frame rate limiter in the Nvidia control panel at least once. Otherwise the API is not able to access the setting for some reason.

Then in the `Do` field put `C:/path/to/app/frltoggle.exe 90`.
In the `Undo` something like `C:/path/to/app/frltoggle.exe 0` (or whatever your previous setting value was).

**Comment by Jankylulu** [comment]
Awesome! I'll give it a try 😆 
Thanks again!
