### ISSUE TITLE
Question about using different framerates

### ISSUE THREAD

**Issue by philhzss** [FrogTheFrog/frl-toggle#2]
Hey Frog,

I have frtoggle (and gsynctoggle) setup in Sunshine as a do/undo command and it's working great. However I have a Deck OLED now and this has created a new "problem" haha, I set frtoggle to 90 when streaming to the Deck because the screen is 90hz and it works great. However my TV is still 60 only.

Very minor "problem" but other than opening the Sunshine config and manually changing the command from 60 -> 90 and vice versa, is there a quick way to switch? In MoonDeck itself I have set all my 16:10 resolutions (1920x1200, 1280x800) to use 90fps, and all my 16:9 resolutions (2560x1440, 3840x2160) to 60fps, which is great because when I'm using the Deck's screen I always go for a 16:10 resolution but my TV is 16:9.

Do you have any ideas of how switching frtoggle from 60 to 90 could be done automatically?

If not don't worry and close this issue it's not an issue at all, just something I was thinking of

Thanks!
Phil

**Comment by FrogTheFrog** [comment]
Hey, try this (copied it from discord, need latest frl-toggle version):

For `do` enter `cmd /C <full path>frltoggle.exe %SUNSHINE_CLIENT_FPS% --save-previous-or-reuse`
- it will automatically set to the stream FPS requested in Moonlight.
- instead of `%SUNSHINE_CLIENT_FPS%` you can set any value 1-1023

For `undo` enter `cmd /C <full path>frltoggle.exe load-file`
- this will set it back to the saved value / your standard setting.
- instead of `load-file` you can set any value 0-1023 (0 for off)

**Comment by philhzss** [comment]
Oh wow that's neat!! Thank you!
Can't test it right now but I updated my sunshine commands and updated ftltoggle. Thank you!!
